### ISSUE TITLE
Openhab 3.0.0 requires API authentication to read item states

### ISSUE THREAD

**Issue by HazeHunter11** [CometVisu/CometVisu#1033] opened 2020-11-04 17:37 UTC
On OpenHab 3.0.0 there is no possibility to retrive the item states due to an authorization on rest level. The server responds with 401 (Unauthorized).

Controlling items is still possible but only one way. So I can set an switch to OFF but can not send the ON command again, because I can not retrive the item state and therefore it always sends off instead of on.

Since Openhab 3.0.0M2 there are two different authentication methods for the API. OAuth2 and as fallback "Basic authentication". The basic authentication must be enabled by the user. By default only OAuth2 is allowed.

**Comment by peuter** [comment] 2020-12-07 17:26
Closing this as a duplicate of https://github.com/openhab/openhab-webui/issues/509

**Closed by peuter** 2020-12-07 17:26 UTC
