### ISSUE TITLE
Diagram popup

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#663] opened 2017-10-25 20:07 UTC
Two issues:
In a touch environment a singe touch should scroll the page and not the (big) diagram. (Unless it's in the full page pop up)

The popup of the (big) diagram shows an empty diagram frame on a Galaxy S7. The other diagram popups (inline and button) are working fine as well as all popups on a tablet (older Android)

**Comment by robert1978** [comment] 2017-10-26 07:39
I can confirm this issue.
For the following test-config works the pop-up works for the left inline-diagram, but delivers an error for the right inline diagram after popup (popup is shown in the background, but with error message in front). Main difference is the previewlabels attribute, which is true for the left, but false for the right diagram in the example.
Error occurs only on Samsung Tablet with Android 7 AND Sony Tablet with Android 4.

![screenshot_2017-10-26-09-35-05](https://user-images.githubusercontent.com/15055578/32040514-573847fe-ba31-11e7-89eb-f1ce2e77788b.png)
2.2 
[visu_config_CVDoku_diagram1.txt](https://github.com/CometVisu/CometVisu/files/1417327/visu_config_CVDoku_diagram1.txt)

**Comment by peuter** [comment] 2017-10-26 15:50
> In a touch environment a singe touch should scroll the page and not the (big) diagram. (Unless it's in the full page pop up)

I don't see how I can configure Flot to pan on two-finger scroll gesture. I surely could catch the one-finger scrolling and use it to scroll the page but prevent it from beeing seen by flot, but that would disable diagram panning completely.
This is another vote for getting rid of the abandoned Flot charts. I don' t see a solution for this problum using them.

**Comment by peuter** [comment] 2017-10-26 20:05
The error message should be fixed with #665. I don't see an empty diagram on my Android Tablet (Lenovo Yoga Tab2, Android 5), maybe the problem is fixed too.

**Comment by ChristianMayer** [comment] 2017-10-27 20:45
At least with the current PR there's an display issue as the "load" is still displayed:
![grafik](https://user-images.githubusercontent.com/10218721/32124555-7d2fccc4-bb68-11e7-8b5f-ac5b977bfd1b.png)

**Comment by ChristianMayer** [comment] 2017-10-27 20:52
> I don't see how I can configure Flot to pan on two-finger scroll gesture. I surely could catch the one-finger scrolling and use it to scroll the page but prevent it from beeing seen by flot, but that would disable diagram panning completely.

I'd disable the diagram scrolling by finger unless it's in the popup.
Reason: when I see the page I want to scroll the page. But the popup is always full page so it make more sense to scroll there the diagram content

> This is another vote for getting rid of the abandoned Flot charts. I don' t see a solution for this problum using them.

The hardest task: finding a versatile plot library that's quick and well maintained. Now and in the future.
And then make it work with the CV...

**Comment by peuter** [comment] 2017-10-28 09:19
Regarding plot libraries there are two options I might consider:
1. https://gionkunz.github.io/chartist-js/
Very lightweight, needs to be checked if we can achieve the same feature set as with flot (there are many plugins, so it could be possible). But this is a rather small project and how well it will be maintained in the future.

2. https://d3js.org/
This is a huge lib with many options (much stuff we do not need currently). I am pretty sure that it is possible to create a flot replacement with the same features as the library has a lot possiblilties. Also I don't see any danger that this project gets abandoned in the near future. Downside is, that it is 220kb script, which is huge compared to the 10kb of chartist. So I think D3 fullfills all of your requirements, but also brings a lot stuff we do not need.

**Comment by peuter** [comment] 2017-10-28 09:49
Diagram scrolling/zooming by finger is disabled now, when not in popup.

**Comment by peuter** [comment] 2017-10-28 10:36
Just found out that D3 is modular and you can create custom builds which contain only the things you need. If it is possible to strip down the size this way, D3 might be the way to go.

**Comment by robert1978** [comment] 2017-10-28 10:48
I also used to scroll in inline widget of diagram, but as this sometimes happened unintentionly, I think that scrolling only in popup is perfect. 
One more remark: enable zoom/scroll could be an option in the axis element (similary as already available in yaxis)

**Comment by ChristianMayer** [comment] 2017-10-28 12:12
D3 looks extremely powerful - with all the advantages and problems that are coming with that.
It really depends how far we could strip that down - as having three frameworks (Qx, legacy jQuery and then D3)  is far of the light weight approach that the CV tries to follow

**Comment by peuter** [comment] 2017-10-28 13:12
Well D3 would replace Flot, so nothing added here. And another plugin dependency to jQuery would be eliminated with this. Actually two, as the PowerSpectrum plugin also uses Flot.

**Comment by peuter** [comment] 2017-10-28 17:26
I think we can close this issue, right?

**Comment by ChristianMayer** [comment] 2017-10-28 18:27
We should await the feedback from @robert1978 as he also had issues.

**Comment by peuter** [comment] 2017-10-29 11:24
One last comment about the D3 topic:
I did a little research to find out more about the D3 packaging. I created a simple line chart with D3 to find out how big a custom package would be. 
Heres what the browsers network console says about the sizes:
All minified Flot js files together: 32.4kb
minified custom D3 package: 37.2kb

This is a size inreasement I could live with. Although it might be become a little bit more when all needed features are included. But the basics are there. Tooltips are missing, but thats only 2kb more.

I suggest that we open a new feature ticket for Flot -> D3 migration, if we decide for D3.

**Comment by robert1978** [comment] 2017-11-05 12:20
Nightly build from 2017-10-25 showed correct behavior. 
Unfortunately actual build from 2017-11-04 shows error message with invalid dimension of plot.
Can you check the test-config in the second post of this issue, it reproduces the problem on my PC (Chrome).

**Closed** 2017-12-24 12:31 UTC
Labels: bug / bugfix
