### ISSUE TITLE
Error on page reload with diagram visible

### ISSUE THREAD

**Issue by joltcoke** [CometVisu/CometVisu#681] opened 2017-11-01 10:10 UTC
If I reload the visu with a page containing a diagram currently visible, I get the following error:

Error: Invalid dimensions for plot, width = 0, height = 100
    at Canvas.resize (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:5:4449)
    at new Canvas (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:5:4271)
    at setupCanvases (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:5:21088)
    at new Plot (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:5:11459)
    at Function.$.plot (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:5:52561)
    at cJ.initDiagram (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:4:8729)
    at cJ. (http://<ip>:8080/cv/build/script/cv-webkit.a48b41ca9405.js:4:13422)
    at cJ.dispatchEvent (http://<ip>:8080/cv/build/script/cv-webkit.js:213:153117)
    at construct.dispatchEvent (http://<ip>:8080/cv/build/script/cv-webkit.js:213:139438)
    at Object.__de (http://<ip>:8080/cv/build/script/cv-webkit.js:213:141418)

Latest GIT version, reproduced with Safari and Chrom on OSX.

**Comment by peuter** [comment] 2017-11-01 15:48
This is a duplicate of #663

**Comment by joltcoke** [comment] 2017-11-01 15:59
I tend to disagree. #663 is (initially) a different issue. The symptoms raised here: https://github.com/CometVisu/CometVisu/issues/663#issuecomment-339579267 are similar, however according to your statement the problem should be fixed by #665. However the fix doesn't work in my case.

I'd vote to keep this open and track the diagram error here instead of mixing various problems in #663.

**Comment by peuter** [comment] 2017-11-01 16:18
However: I tried to reproduce the issue with Chrome 62 (LInux) and Safari 11 in macOS in build an source versions: never happened. So I don't see anything that I can do about it.

**Comment by joltcoke** [comment] 2017-11-01 16:25
The problem doesn’t occur with the source version, only with the build version. Sorry, forgot to mention that.

Does that indicate a problem with my build?

**Comment by peuter** [comment] 2017-11-01 16:31
Thats hard to say. We had this error a couple of times, with different causes. The problem is that a dimension (width or height) of the DOMElement where the Flot chart library wants to point its chart is 0 at that moment. I fixes several bugs around that problem and with the latest version is was quite stable.

Mayby you can run a `./generate.py distclean` and generate a new build after that. But I don't really expect that it fixes the problem. Sorry currently I have no idea what to do here.

**Comment by peuter** [comment] 2017-11-01 16:37
A log would be a last option. Bit I tend to believe that this is some kind of timing issue, which are highly device dependent and if that is true, a cannot reproduce the error by replaying the log in my devices.
The second possibility is that has to do with your config (e.g. many diagrams with a lot of data, or whatever), in this case a log would help.

**Comment by robert1978** [comment] 2017-11-05 18:36
I have the same issue in the nightly Build from 4.11., but already on initial load, not only reload.

**Comment by peuter** [comment] 2018-03-14 16:58
@robert1978 can you confirm that the error is gone with the latest nightly build?

**Comment by robert1978** [comment] 2018-03-14 20:54
Hy Tobias!
I was quite busy the last months.....
I still get the error "invalid dimensions for plot..." on reload.
Nevertheless I could no cause any crash just by clicking through the visu packes, open/close diagram popups, pagejumps etc. => seems at least improved. I keep it as productive on my tablet to watch.
Same crash during reload happens in Firefox & Chrome on my PC/Win10 and in Ubuntu17.04/Firefox as well. I also tried a small config => same behavior.

Interestingly the demo config does not crash, although there is a diagram on the main page.
I could narrow the behavior down to the following point: if width="xxx" and height="yyy" is used, there is no problem during reload. If this two parameters are omitted and only colspan/rowspan is used, the error occurs. Hope this helps a bit.
Robert

**Comment by peuter** [comment] 2018-03-15 15:52
@robert1978 Can you provide a small config to reproduce the error, because I can't. If I open the page with the diagram in my config directly (has no sizes defined) I don't see any error.

A log file would be even better.

**Comment by robert1978** [comment] 2018-03-15 19:25
Here a log of a reload error. 
[CometVisu-replay-20180315-200103.zip](https://github.com/CometVisu/CometVisu/files/1816752/CometVisu-replay-20180315-200103.zip)
and the xml-file.
[visu_config_diagram2.zip](https://github.com/CometVisu/CometVisu/files/1816754/visu_config_diagram2.zip)

Interestingly I get the error on reload now, even with width/height given. If I modify the xml it loads correctly, if I reload it crashes. Seems to be a link to the caching. 
I can confirm this further: if I use enableCache=false, I can reload even without width/height.
Hope this helps.
Robert

here a reload with enableCache=false:
[CometVisu-replay-20180315-202415.zip](https://github.com/CometVisu/CometVisu/files/1816810/CometVisu-replay-20180315-202415.zip)

**Comment by peuter** [comment] 2018-03-15 20:50
The caching hint did the trick. I usually use the source version to debug and test the code (which has cache disabled by default). So I never has the error. When I enable the cache I can reproduce the error. Now I can work on a fix. Thanks for the hint.

**Comment by robert1978** [comment] 2018-03-15 22:39
Great news! I just was lucky to recognize this effect....

**Comment by peuter** [comment] 2018-03-31 14:22
I've just manually created and uploaded a new nightly build which hopefully finally solves this issue. 
https://bintray.com/cometvisu/CometVisu/download_file?file_path=CometVisu-0.11.0-dev-20180331141712.zip

@robert1978 Can you confirm that its fixed?

**Comment by robert1978** [comment] 2018-03-31 18:20
Just tried. Looks fine. I can reload with diagrams on any page in the visu!
Thanks
Robert

**Comment by peuter** [comment] 2018-03-31 18:30
Thanks, closing this now.

**Closed by peuter** 2018-03-31 18:30 UTC
Labels: bug / bugfix, duplicate
